module.exports = Object.freeze({
  EXECUTIVE: "EXECUTIVE",
  OPERATIONS: "OPERATIONS",
  CUSTOMER_RELATIONS: "CUSTOMER_RELATIONS",
  FINANCE: "FINANCE",
  MARKETING: "MARKETING",
  HUMAN_RESOURCES: "HUMAN_RESOURCES",
  AUDIT: "AUDIT",
  TRANSPORT: "TRANSPORT",
});
