const group = (values) => Object.freeze(Object.fromEntries(values.map((value) => [value, value])));

const PERMISSION_GROUPS = Object.freeze({
  SECURITY_SYSTEM: group(["USER_VIEW", "USER_STATUS_MANAGE", "USER_ROLE_MANAGE", "SECURITY_ADMIN", "SYSTEM_SETTINGS_VIEW", "SYSTEM_SETTINGS_MANAGE"]),
  ORGANIZATION_HR: group(["DEPARTMENT_VIEW", "DEPARTMENT_MANAGE", "EMPLOYEE_VIEW", "EMPLOYEE_MANAGE", "REPORTING_LINE_MANAGE", "EMPLOYMENT_SENSITIVE_VIEW"]),
  PROPERTY_OPERATIONS: group(["PROPERTY_VIEW_PUBLIC", "PROPERTY_VIEW_INTERNAL", "PROPERTY_CREATE", "PROPERTY_UPDATE_OWN", "PROPERTY_UPDATE_ANY", "PROPERTY_ASSIGN", "PROPERTY_SUBMIT_REVIEW", "PROPERTY_REVIEW", "PROPERTY_APPROVE", "PROPERTY_PUBLISH", "PROPERTY_ARCHIVE", "PROPERTY_SUBMISSION_VIEW_ALL", "PROPERTY_SUBMISSION_VIEW_ASSIGNED", "PROPERTY_SUBMISSION_ASSIGN_MANAGER", "PROPERTY_SUBMISSION_ASSIGN_AGENT", "PROPERTY_SUBMISSION_REASSIGN", "PROPERTY_SUBMISSION_UPDATE_WORKFLOW"]),
  CASE_INSPECTION_LISTING: group(["CASE_VIEW", "CASE_CREATE", "CASE_ASSIGN", "CASE_MANAGE", "INSPECTION_VIEW", "INSPECTION_SCHEDULE", "INSPECTION_COMPLETE", "INSPECTION_REVIEW", "LISTING_DRAFT_VIEW", "LISTING_DRAFT_CREATE", "LISTING_DRAFT_SUBMIT", "LISTING_DRAFT_REVIEW"]),
  MEDIA: group(["MEDIA_UPLOAD_ORIGINAL", "MEDIA_PROCESS", "MEDIA_REVIEW", "MEDIA_APPROVE"]),
  CUSTOMER_RELATIONS: group(["INQUIRY_VIEW", "INQUIRY_ASSIGN", "INQUIRY_RESPOND", "PROPERTY_REQUEST_VIEW", "PROPERTY_REQUEST_ASSIGN", "PROPERTY_REQUEST_RESPOND", "CUSTOMER_CONCERN_VIEW", "CUSTOMER_CONCERN_ASSIGN", "CUSTOMER_CONCERN_RESPOND", "CUSTOMER_CONCERN_ESCALATE", "COORDINATION_REQUEST_CREATE", "COORDINATION_REQUEST_RESPOND"]),
  COMMERCIAL_OPERATIONS: group(["VIEWING_VIEW", "VIEWING_ASSIGN", "VIEWING_COORDINATE", "VIEWING_OPERATIONAL_STATUS_MANAGE", "OFFER_VIEW", "OFFER_ASSIGN", "OFFER_MANAGE", "DEAL_VIEW", "DEAL_CREATE", "DEAL_MANAGE", "DEAL_CLOSE"]),
  FINANCE: group(["PAYMENT_VIEW", "PAYMENT_RECORD", "PAYMENT_RECONCILE", "PAYMENT_REVERSE", "COMMISSION_VIEW", "COMMISSION_MANAGE", "FINANCIAL_REPORT_VIEW"]),
  MARKETING: group(["MARKETING_VIEW", "CAMPAIGN_CREATE", "CAMPAIGN_MANAGE", "PROMOTIONAL_CONTENT_MANAGE", "FEATURED_PROPERTY_MANAGE", "CAMPAIGN_ANALYTICS_VIEW"]),
  RECORDS: group(["DOCUMENT_VIEW", "DOCUMENT_UPLOAD", "DOCUMENT_MANAGE", "TASK_VIEW", "TASK_CREATE", "TASK_ASSIGN", "TASK_MANAGE", "FEEDBACK_SUMMARY_VIEW", "FEEDBACK_RAW_VIEW", "FEEDBACK_REVIEW", "AUDIT_LOG_VIEW"]),
});

const PERMISSIONS = Object.freeze(Object.assign({}, ...Object.values(PERMISSION_GROUPS)));
const ALL_PERMISSIONS = Object.freeze(Object.values(PERMISSIONS));

module.exports = { PERMISSIONS, PERMISSION_GROUPS, ALL_PERMISSIONS };
