const REFERENCE_PREFIXES = {
  INQUIRY: "INQ",
  VIEWING_REQUEST: "VIEW",
  OFFER: "OFF",
  DEAL: "DEAL",
  TASK: "TASK",
  DOCUMENT: "DOC",
  FEEDBACK: "FDBK",
  PROPERTY_REQUEST: "PREQ",
};

module.exports = REFERENCE_PREFIXES;
