const ROLES = Object.freeze({
  SUPER_ADMIN: "SUPER_ADMIN",
  GENERAL_MANAGER: "GENERAL_MANAGER",
  OPERATIONS_MANAGER: "OPERATIONS_MANAGER",
  AGENT: "AGENT",
  CUSTOMER_RELATIONS_MANAGER: "CUSTOMER_RELATIONS_MANAGER",
  CUSTOMER_RELATIONS_OFFICER: "CUSTOMER_RELATIONS_OFFICER",
  FINANCE_MANAGER: "FINANCE_MANAGER",
  FINANCE_OFFICER: "FINANCE_OFFICER",
  MARKETING_MANAGER: "MARKETING_MANAGER",
  MARKETING_OFFICER: "MARKETING_OFFICER",
  HR_MANAGER: "HR_MANAGER",
  HR_OFFICER: "HR_OFFICER",
  AUDITOR: "AUDITOR",
  OWNER: "OWNER",
  CUSTOMER: "CUSTOMER",
  ADMIN: "ADMIN",
});

const LEGACY_ROLES = Object.freeze({
  ADMIN: "Admin",
  AGENT: "Agent",
  OWNER: "Owner",
  CUSTOMER: "Customer",
});

const ROLE_ALIASES = Object.freeze({
  [LEGACY_ROLES.ADMIN]: ROLES.ADMIN,
  [LEGACY_ROLES.AGENT]: ROLES.AGENT,
  [LEGACY_ROLES.OWNER]: ROLES.OWNER,
  [LEGACY_ROLES.CUSTOMER]: ROLES.CUSTOMER,
  ...Object.fromEntries(Object.values(ROLES).map((role) => [role, role])),
});

const USER_ROLE_VALUES = Object.freeze([
  ...new Set([...Object.values(LEGACY_ROLES), ...Object.values(ROLES)]),
]);

module.exports = { ROLES, LEGACY_ROLES, ROLE_ALIASES, USER_ROLE_VALUES };
